### ISSUE TITLE
Spaces are missing in the HTML file

### ISSUE THREAD

**Issue by NeilAn99** [rokaicker/StaticSiteGenerator#3]
There are multiple places where a space is missing from the HTML file. For example:
![newline 2](https://user-images.githubusercontent.com/54966170/189703566-0d24c89d-c611-4954-bee4-ef7fc7457928.JPG)
and
![newline](https://user-images.githubusercontent.com/54966170/189703652-a4edcf60-01cb-4898-9538-1e9d3d06c077.JPG)
This bug occurs for all files.

**Comment by rokaicker** [comment]
i beleive i've corrected the spacing issue by fixing generateSite() in helper.js
