### ISSUE TITLE
Title and header are incorrectly created in some cases

### ISSUE THREAD

**Issue by NeilAn99** [rokaicker/StaticSiteGenerator#4]
The HTML files are not created properly if there are 2 new lines found in the text file somewhere not after the first line. For example:
![title bug](https://user-images.githubusercontent.com/54966170/189707004-9fca9afc-e7bf-4137-b83a-d44372c2e71f.JPG)
and
![title bug html](https://user-images.githubusercontent.com/54966170/189707063-93ebe144-c49e-4bdf-9b99-44d994b9c1df.JPG)

Also, the title and header should only check the first line of the text file.

**Comment by rokaicker** [comment]
issue has been fixed
