### ISSUE TITLE
Cannot run the rohan-ssg command directly on a Windows terminal

### ISSUE THREAD

**Issue by NeilAn99** [rokaicker/StaticSiteGenerator#5]
In a Windows terminal (ex. Command prompt), an error occurs if trying to run the `rohan-ssg` command directly without using the `node` command before it. For example:
![image](https://user-images.githubusercontent.com/54966170/189709875-6cc803af-9a27-49e2-ba2a-7b59354d51d0.png)

**Comment by rokaicker** [comment]
wasn't sure how to fix this, I was unable to call "rohan-ssg" without prepending node to the front when using powershell or command prompt, so in the README i specified the use of a bash shell as a workaround.
