### ISSUE TITLE
Better formatting for HTML files

### ISSUE THREAD

**Issue by NeilAn99** [rokaicker/StaticSiteGenerator#6]
The generated HTML files could be formatted better so they are more human readable. The \<p> tags are all put into 1 line, and there is some extra whitespace before every line. For example:
![image](https://user-images.githubusercontent.com/54966170/189711895-5c257d0a-57fb-425c-9606-bd5306d42025.png)

**Comment by rokaicker** [comment]
corrected code to make it easier to read
